import { StyleSheet } from '@react-pdf/renderer';

export const COLORS = {
  navy: '#1F3A5F',
  blue: '#2E75B6',
  body: '#1a1a1a',
  muted: '#666666',
  rule: '#CCCCCC',
  tableHeaderBg: '#2E75B6',
  tableHeaderText: '#FFFFFF',
  tableAltBg: '#F5F8FB',
  pricingRowBg: '#E8F0F8',
  pricingTotalBg: '#2E75B6',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 72,
    paddingBottom: 72,
    paddingHorizontal: 72,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: COLORS.body,
    lineHeight: 1.6,
  },
  cover: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.blue,
    borderBottomStyle: 'solid',
  },
  coverBrand: {
    fontSize: 36,
    color: COLORS.navy,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: -0.5,
    marginBottom: 2,
  },
  coverTag: {
    fontSize: 11,
    color: COLORS.muted,
    fontStyle: 'italic',
    marginBottom: 24,
  },
  coverLabel: {
    fontSize: 11,
    color: COLORS.blue,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  coverTitle: {
    fontSize: 26,
    color: COLORS.navy,
    fontFamily: 'Helvetica-Bold',
    lineHeight: 1.15,
    marginBottom: 6,
  },
  coverSub: {
    fontSize: 14,
    color: COLORS.blue,
    marginBottom: 24,
  },
  coverMetaBlock: {
    marginBottom: 12,
    fontSize: 11,
    lineHeight: 1.6,
  },
  coverMetaLabel: {
    color: COLORS.navy,
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
  },
  h1: { fontSize: 24, color: COLORS.navy, fontFamily: 'Helvetica-Bold', marginBottom: 6, lineHeight: 1.2 },
  h2: {
    fontSize: 16,
    color: COLORS.navy,
    fontFamily: 'Helvetica-Bold',
    marginTop: 22,
    marginBottom: 10,
    paddingBottom: 4,
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.blue,
    borderBottomStyle: 'solid',
  },
  h3: { fontSize: 13, color: COLORS.blue, fontFamily: 'Helvetica-Bold', marginTop: 16, marginBottom: 6 },
  h4: { fontSize: 11, color: COLORS.navy, fontFamily: 'Helvetica-Bold', marginTop: 10, marginBottom: 4 },
  paragraph: { marginBottom: 8 },
  bold: { fontFamily: 'Helvetica-Bold' },
  italic: { fontFamily: 'Helvetica-Oblique' },
  boldItalic: { fontFamily: 'Helvetica-BoldOblique' },
  list: { marginVertical: 4, marginBottom: 10, paddingLeft: 14 },
  listItem: { flexDirection: 'row', marginBottom: 4 },
  listBullet: { width: 16, fontSize: 11 },
  listText: { flex: 1, fontSize: 11 },
  table: {
    marginVertical: 8,
    marginBottom: 14,
    borderWidth: 0.5,
    borderColor: COLORS.rule,
    borderStyle: 'solid',
  },
  tableRow: { flexDirection: 'row' },
  tableHeaderCell: {
    backgroundColor: COLORS.tableHeaderBg,
    color: COLORS.tableHeaderText,
    padding: 7,
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    borderRightWidth: 0.5,
    borderRightColor: COLORS.rule,
    borderRightStyle: 'solid',
  },
  tableCell: {
    padding: 7,
    fontSize: 10.5,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.rule,
    borderTopStyle: 'solid',
    borderRightWidth: 0.5,
    borderRightColor: COLORS.rule,
    borderRightStyle: 'solid',
  },
  tableCellAlt: { backgroundColor: COLORS.tableAltBg },
  pricingRow: { backgroundColor: COLORS.pricingRowBg, fontFamily: 'Helvetica-Bold' },
  pricingTotal: {
    backgroundColor: COLORS.pricingTotalBg,
    color: '#FFFFFF',
    fontFamily: 'Helvetica-Bold',
  },
  blockquote: {
    borderLeftWidth: 3,
    borderLeftColor: COLORS.blue,
    borderLeftStyle: 'solid',
    paddingLeft: 14,
    paddingVertical: 8,
    marginVertical: 10,
    backgroundColor: COLORS.tableAltBg,
    color: '#444444',
    fontStyle: 'italic',
  },
});
